spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
mybatis:
  mapper-locations: classpath:*.xml
  type-aliases-package: ru.prod.tracker.model
  configuration:
    map-underscore-to-camel-case: true
jwt:
  secret: c2VjdXJlLXNlY3JldC1rZXktZm9yLWp3dC10YXNrLXRpbWUtdHJhY2tlci1hcGk=
  expiration-ms: 86400000

logging:
  level:
    org.springdoc: DEBUG